spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true # প্রোডাকশনে এরর ট্র্যাকিং এর জন্য সাময়িকভাবে true রাখতে পারেন
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # PostgreSQL এ LOB হ্যান্ডলিং এর জন্য এটি জরুরি

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# Server Configuration
server:
  servlet:
    session:
      persistent: false
      store-dir: sessions

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

  jwtSecret: ${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
  jwtExpirationMs: ${JWT_EXPIRATION:86400000}
  default-admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    email: ${ADMIN_EMAIL:admin@gmail.com}

logging:
  level:
    com.lms.dev: ${APP_LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}